---
title: "Assignment 2"
author: "630516am and 590049bm"
date: "23 Nov 2021"
output: pdf_document
---

```{r setup, include=FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
knitr::opts_chunk$set(echo = TRUE,
                      out.width = "250pt", 
                      out.height = "200pt", 
                      fig.align = "center",
                      size = 'small', 
                      warning = FALSE, 
                      message = FALSE)
f <- function(x) format(round(x, 2), big.mark=",")
gm <- list(
  list("raw" = "nobs", "clean" = "N"),
  list("raw" = "adj.r.squared", "clean" = "Adj. R2", fmt = f))
# ici on va mettre toutes les bibliotheques
library(tidyverse); library(modelsummary); library(car)
```

## Question 1

```{r}
set.seed(2021)
```


```{r}
b0 <- 3
b1 <- 5
b2 <- 8

gamma <- 1 

x1 <- rnorm(5000, mean = 1, sd = 1)
x2 <- rnorm(5000, mean = 2, sd = 1)

z <- rgamma(5000, shape = 1.2, scale = 1.1)

sigma_sq <- 1*exp(gamma*z)
epsilon <- rnorm(5000, mean = 0, sd = sqrt(sigma_sq))

y <- b0 + b1*x1 + b2*x2 + epsilon

```

```{r}
model1 <- lm(y ~ x1 + x2)

modelsummary(model1, 
             vcov = c("iid", "HC0"), 
             gof_map = gm, 
             stars = T)

```

```{r}
lmtest::bptest(formula = y ~ x1 + x2)
```

```{r}
gamma <- 0

sigma_sq <- 1*exp(gamma*z)
epsilon <- rnorm(5000, mean = 0, sd = sqrt(sigma_sq))

y <- b0 + b1*x1 + b2*x2 + epsilon
```


```{r}
model1 <- lm(y ~ x1 + x2)
model2 <- lm(y ~ x1 + x2, weights = sigma_sq)

```



## Question 2


1. Show that the OLS estimator of the parameter $\beta$ is not consistent

The estimate coefficient is:


$$
\hat \beta = (D^TD)^{-1}D^T C_ = (D^T D)^{-1}(\beta  D + \epsilon) = 
$$



